// constants.js
const PATH_TO_PUBLIC_KEY_FILE = 'pubkey';
const PATH_TO_PRIVATE_KEY_FILE = 'prvkey';
const DEVICE_INTERNAL_STATE = new Buffer('11db7a0b547fe71ffe4b32a3b802a401', 'hex');
const DEVICE_SSTORE_SECRET_KEY = new Buffer('213260e3953d86115f72b8fca15ae7b1', 'hex');

exports.PATH_TO_PUBLIC_KEY_FILE = PATH_TO_PUBLIC_KEY_FILE;
exports.PATH_TO_PRIVATE_KEY_FILE = PATH_TO_PRIVATE_KEY_FILE;
exports.DEVICE_INTERNAL_STATE = DEVICE_INTERNAL_STATE;
exports.DEVICE_SSTORE_SECRET_KEY = DEVICE_SSTORE_SECRET_KEY;
