all: trivial.c trivial_1 trivial_2 trivial_3 trivial_4 trivial_5
	chmod a+x ./exec.sh
	chmod a+x ./stop.sh
	gcc trivial.c -o ./bin/trivial
	gcc trivial.c -o ./bin/trivial_6

trivial_1: trivial_1.c
	gcc trivial_1.c -o ./bin/trivial_1
trivial_2: trivial_2.c
	gcc trivial_2.c -o ./bin/trivial_2
trivial_3: trivial_3.c
	gcc trivial_3.c -o ./bin/trivial_3
trivial_4: trivial_4.c
	gcc trivial_4.c -o ./bin/trivial_4
trivial_5: trivial_5.c
	gcc trivial_5.c -o ./bin/trivial_5